name: classified_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.13
  flutter_secure_storage: ^6.0.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  rounded_loading_button: ^2.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#fffffff"
  image: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
